### ISSUE TITLE
rescue() should receive the original type

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_typecrawler#18]
Currently what `rescue()` receives is the underlying type, if the original type is an abstract. Because the type has gone through the `plainAbstract` branch. In the case of Int64, during rescue I need to check the underlying type which is platform-specific, so it is not so friendly.

**Comment by back2dos** [comment]
I'm gonna go with "it's supposed to be that way". We added `Generator.drive` so that one can intercept everything *before* it enters further logic (type following and what not).

That said I'm open to discussing improvements. Let me just throw out two ideas (not mutually exclusive):

1. give the caller control over whether `plainAbstract` is used at all - either per flag or by not doing it automatically but rather letting the generator make that distinction in `drive` or `rescue`
2. add further branches for numeric types

**Comment by kevinresol** [comment]
Can you explain a bit:

1. What is plainAbstract actually? 
2. What is the difference between drive and rescue?

**Comment by back2dos** [comment]
1. a "plain abstract" is an abstract that has both direct `to` and `from` its underlying type, which makes both types fully equivalent (any value of that is valid for the abstract is valid for the underlying type and vice versa) ... so the basic assumption derived from this equivalency is that it should get the same treatment as the underlying type.
2. `drive` passes control to the generator, with the actual crawling function as one argument, that the generator can call when it wishes to recurse into the type, which among other things means following typedefs and said "plain abtracts". If you go with the trivial drive implementation we have everywhere right now, then the crawler basically recurses "on autopilot". But you can also fully control the recursion by sticking logic into the drive function. The crawler calls `drive` on every type it encounters, to let the generator drive the recursion further and `rescue` only if it cannot figure out what to do about a particular type once it has reduced it.
